/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorColores;
import Modelos.textoSombra;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.SwingUtilities;

/**
 *
 * @author domin
 */
public class PanelAdminn extends javax.swing.JFrame implements Runnable {

    String hora, minutos, segundos;
    Thread hilo;
    private boolean menuVisible = true;

    CardLayout vista;
    DabroardPanel dabroardPanel = new DabroardPanel();
    

    public PanelAdminn() {

        initComponents();
        this.setLayout(null); // o el panel contenedor.setLayout(null)

        TxtBuscar.setOpaque(false);
        textoSombra usuario = new textoSombra("Busca cualquier cosa aquí..", TxtBuscar);
        fechaHora();

        ControladorColores controladorColores = new ControladorColores(this);
        vista = (CardLayout) pnl_vista_principal.getLayout();
        vista.show(pnl_vista_principal, "card2");

    }

    public void hora() {
        Calendar calendar = new GregorianCalendar();
        Date horaActual = new Date();
        calendar.setTime(horaActual);
        int horaDia = calendar.get(Calendar.HOUR_OF_DAY);

        hora = calendar.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendar.get(Calendar.HOUR_OF_DAY) : "0" + calendar.get(Calendar.HOUR_OF_DAY);
        minutos = calendar.get(Calendar.MINUTE) > 9 ? "" + calendar.get(Calendar.MINUTE) : "0" + calendar.get(Calendar.MINUTE);
        segundos = calendar.get(Calendar.SECOND) > 9 ? "" + calendar.get(Calendar.SECOND) : "0" + calendar.get(Calendar.SECOND);

        String saludo;
        if (horaDia >= 5 && horaDia < 12) {
            saludo = "Buenos días";
        } else if (horaDia >= 12 && horaDia < 19) {
            saludo = "Buenas tardes";
        } else {
            saludo = "Buenas noches";
        }

        // Mostrar el saludo en el JTextField
        txtTiemp.setText(saludo);
    }

    public static String fecha() {
        Date fecha = new Date();
        // Formato: día número + mes en texto + año (en español)
        SimpleDateFormat formatoFecha = new SimpleDateFormat("d MMMM yyyy", new Locale("es", "ES"));
        return formatoFecha.format(fecha);
    }

    public void fechaHora() {
        JlbDias.setText(fecha());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
    }

    public void run() {
        Thread norma = Thread.currentThread();
        while (norma == hilo) {
            hora();
            JlbHora.setText(hora + ":" + minutos + ":" + segundos);
            try {
                Thread.sleep(1000); // Espera 1 segundo
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnDasboard1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnDasboard2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnDasboard4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnDasboard5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnDasboard6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnDasboard7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnDasboard8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxtBuscar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JlbDias = new javax.swing.JLabel();
        JlbHora = new javax.swing.JLabel();
        txtTiemp = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        pnl_vista_principal = new javax.swing.JPanel();
        PanelGrafico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(237, 241, 245));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(40, 51, 66));
        pnlMenu.setForeground(new java.awt.Color(0, 0, 0));
        pnlMenu.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(29, 36, 46));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("v 1.0.0");

        jLabel9.setBackground(new java.awt.Color(160, 167, 173));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sofware UP © 2025");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(16, 16, 16))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel13);
        jPanel13.setBounds(0, 580, 240, 50);

        jSeparator1.setBackground(new java.awt.Color(29, 36, 46));
        jSeparator1.setForeground(new java.awt.Color(29, 36, 46));
        pnlMenu.add(jSeparator1);
        jSeparator1.setBounds(0, 500, 240, 10);

        jSeparator2.setBackground(new java.awt.Color(29, 36, 46));
        jSeparator2.setForeground(new java.awt.Color(29, 36, 46));
        pnlMenu.add(jSeparator2);
        jSeparator2.setBounds(0, 240, 240, 10);

        btnDasboard1.setBackground(new java.awt.Color(40, 51, 66));
        btnDasboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDasboard1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-home-25.png"))); // NOI18N
        jLabel6.setText("       Home        ");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnDasboard1Layout = new javax.swing.GroupLayout(btnDasboard1);
        btnDasboard1.setLayout(btnDasboard1Layout);
        btnDasboard1Layout.setHorizontalGroup(
            btnDasboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnDasboard1Layout.setVerticalGroup(
            btnDasboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlMenu.add(btnDasboard1);
        btnDasboard1.setBounds(0, 80, 240, 70);

        btnDasboard2.setBackground(new java.awt.Color(40, 51, 66));
        btnDasboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDasboard2MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-home-25.png"))); // NOI18N
        jLabel7.setText("       Home        ");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setVerifyInputWhenFocusTarget(false);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnDasboard2Layout = new javax.swing.GroupLayout(btnDasboard2);
        btnDasboard2.setLayout(btnDasboard2Layout);
        btnDasboard2Layout.setHorizontalGroup(
            btnDasboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnDasboard2Layout.setVerticalGroup(
            btnDasboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlMenu.add(btnDasboard2);
        btnDasboard2.setBounds(0, 0, 240, 70);

        btnDasboard4.setBackground(new java.awt.Color(40, 51, 66));
        btnDasboard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDasboard4MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-home-25.png"))); // NOI18N
        jLabel8.setText("       Home        ");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setVerifyInputWhenFocusTarget(false);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnDasboard4Layout = new javax.swing.GroupLayout(btnDasboard4);
        btnDasboard4.setLayout(btnDasboard4Layout);
        btnDasboard4Layout.setHorizontalGroup(
            btnDasboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnDasboard4Layout.setVerticalGroup(
            btnDasboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlMenu.add(btnDasboard4);
        btnDasboard4.setBounds(0, 160, 240, 70);

        btnDasboard5.setBackground(new java.awt.Color(40, 51, 66));
        btnDasboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDasboard5MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-home-25.png"))); // NOI18N
        jLabel12.setText("       Home        ");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel12.setVerifyInputWhenFocusTarget(false);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnDasboard5Layout = new javax.swing.GroupLayout(btnDasboard5);
        btnDasboard5.setLayout(btnDasboard5Layout);
        btnDasboard5Layout.setHorizontalGroup(
            btnDasboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnDasboard5Layout.setVerticalGroup(
            btnDasboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlMenu.add(btnDasboard5);
        btnDasboard5.setBounds(0, 260, 240, 70);

        btnDasboard6.setBackground(new java.awt.Color(40, 51, 66));
        btnDasboard6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDasboard6MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-home-25.png"))); // NOI18N
        jLabel15.setText("       Home        ");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel15.setVerifyInputWhenFocusTarget(false);
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnDasboard6Layout = new javax.swing.GroupLayout(btnDasboard6);
        btnDasboard6.setLayout(btnDasboard6Layout);
        btnDasboard6Layout.setHorizontalGroup(
            btnDasboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnDasboard6Layout.setVerticalGroup(
            btnDasboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlMenu.add(btnDasboard6);
        btnDasboard6.setBounds(0, 340, 240, 70);

        btnDasboard7.setBackground(new java.awt.Color(40, 51, 66));
        btnDasboard7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDasboard7MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-home-25.png"))); // NOI18N
        jLabel16.setText("       Home        ");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel16.setVerifyInputWhenFocusTarget(false);
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnDasboard7Layout = new javax.swing.GroupLayout(btnDasboard7);
        btnDasboard7.setLayout(btnDasboard7Layout);
        btnDasboard7Layout.setHorizontalGroup(
            btnDasboard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnDasboard7Layout.setVerticalGroup(
            btnDasboard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDasboard7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlMenu.add(btnDasboard7);
        btnDasboard7.setBounds(0, 420, 240, 70);

        btnDasboard8.setBackground(new java.awt.Color(40, 51, 66));
        btnDasboard8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDasboard8MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-exit-24.png"))); // NOI18N
        jLabel17.setText("       Cerrar Sesión        ");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel17.setVerifyInputWhenFocusTarget(false);
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnDasboard8Layout = new javax.swing.GroupLayout(btnDasboard8);
        btnDasboard8.setLayout(btnDasboard8Layout);
        btnDasboard8Layout.setHorizontalGroup(
            btnDasboard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDasboard8Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        btnDasboard8Layout.setVerticalGroup(
            btnDasboard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDasboard8Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(15, 15, 15))
        );

        pnlMenu.add(btnDasboard8);
        btnDasboard8.setBounds(0, 520, 240, 60);

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 700));

        jPanel3.setBackground(new java.awt.Color(29, 36, 46));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sofware UP");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        jPanel1.setBackground(new java.awt.Color(247, 250, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtBuscar.setBackground(new java.awt.Color(227, 235, 243));
        TxtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtBuscar.setForeground(new java.awt.Color(51, 51, 51));
        TxtBuscar.setBorder(null);
        TxtBuscar.setCaretColor(new java.awt.Color(51, 51, 51));
        TxtBuscar.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 340, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Busqueda.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 40));

        JlbDias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JlbDias.setForeground(new java.awt.Color(51, 51, 51));
        JlbDias.setText("DD/MM/YY");
        jPanel1.add(JlbDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, 20));

        JlbHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JlbHora.setForeground(new java.awt.Color(51, 51, 51));
        JlbHora.setText("00:00:00");
        jPanel1.add(JlbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, -1, 20));

        txtTiemp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTiemp.setForeground(new java.awt.Color(51, 51, 51));
        txtTiemp.setText("Buenos dias");
        jPanel1.add(txtTiemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 180, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tiempo.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 10, 25));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TiempoGrande.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 0, 30, 40));

        btnMenu.setBackground(new java.awt.Color(247, 250, 253));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-menu-30.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1130, 70));

        pnl_vista_principal.setBackground(new java.awt.Color(237, 241, 245));
        pnl_vista_principal.setLayout(new java.awt.CardLayout());

        PanelGrafico.setBackground(new java.awt.Color(237, 241, 245));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout PanelGraficoLayout = new javax.swing.GroupLayout(PanelGrafico);
        PanelGrafico.setLayout(PanelGraficoLayout);
        PanelGraficoLayout.setHorizontalGroup(
            PanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        PanelGraficoLayout.setVerticalGroup(
            PanelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGraficoLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pnl_vista_principal.add(PanelGrafico, "card2");

        getContentPane().add(pnl_vista_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 1130, 700));

        jPanel2.setBackground(new java.awt.Color(237, 241, 245));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = this.pnlMenu.getX();
        if (menuVisible) {
            Animacion.Animacion.mover_izquierda(0, -240, 2, 2, pnlMenu);

            pnlMenu.setLocation(-188, pnlMenu.getY());
            menuVisible = false;
        } else {
            Animacion.Animacion.mover_derecha(-240, 0, 2, 2, pnlMenu);
            pnlMenu.setLocation(0, pnlMenu.getY());
            menuVisible = true;
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDasboard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDasboard1MouseClicked
        pnl_vista_principal.add(dabroardPanel, "alta");
        vista.show(pnl_vista_principal, "alta");
    }//GEN-LAST:event_btnDasboard1MouseClicked

    private void btnDasboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDasboard2MouseClicked
          vista.show(pnl_vista_principal, "card2");
    }//GEN-LAST:event_btnDasboard2MouseClicked

    private void btnDasboard4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDasboard4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDasboard4MouseClicked

    private void btnDasboard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDasboard5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDasboard5MouseClicked

    private void btnDasboard6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDasboard6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDasboard6MouseClicked

    private void btnDasboard7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDasboard7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDasboard7MouseClicked

    private void btnDasboard8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDasboard8MouseClicked
        JframeLogin login = new JframeLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDasboard8MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbDias;
    private javax.swing.JLabel JlbHora;
    private javax.swing.JPanel PanelGrafico;
    private javax.swing.JTextField TxtBuscar;
    public javax.swing.JPanel btnDasboard1;
    public javax.swing.JPanel btnDasboard2;
    public javax.swing.JPanel btnDasboard4;
    public javax.swing.JPanel btnDasboard5;
    public javax.swing.JPanel btnDasboard6;
    public javax.swing.JPanel btnDasboard7;
    public javax.swing.JPanel btnDasboard8;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnl_vista_principal;
    private javax.swing.JLabel txtTiemp;
    // End of variables declaration//GEN-END:variables
}
